apiVersion: v1
kind: ConfigMap
metadata:
  name: openpanel-config
  namespace: openpanel
data:
  NODE_ENV: "production"
  API_PORT: "3000"
  NEXT_PUBLIC_API_URL: "http://openpanel-api:3333"
  NEXT_PUBLIC_DASHBOARD_URL: "http://openpanel.local"
