apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openpanel-ingress
  namespace: openpanel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: openpanel.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openpanel-start
                port:
                  number: 3000
    - host: api.openpanel.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openpanel-api
                port:
                  number: 3333
