apiVersion: v1
kind: Namespace
metadata:
  name: openpanel
  labels:
    app.kubernetes.io/part-of: openpanel
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    app.kubernetes.io/part-of: backup
