---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-credentials
  namespace: openpanel
spec:
  encryptedData:
    CLICKHOUSE_PASSWORD: AgCiOZdIdEakjPjx4G+ZFgcd43TzUTR07xTNl9/OSOdz2QYAx24vkyuJ3T6Vc7sUU2psWcavS/pQDICXerLgcdZqrt2z92IPk21XOh7sh2VGTFK1LV1yQWnQ+6NqxjEA+0YkV41ELRCl9LyeGhOHXFyMCKRyDfa27x64SPKBcWIQPkVQxBq+EBaIH/BuVjvyIQBK+md7BY1EdfBREC6h9nAh9d9LihvCAuXQnBm+PcUo94Az5SBrVhWKQ9/kXqyf+JgdjWt1xGJ4MYFPL4CbCcLRMK+GlRjZ6laMun1eNuHMqf6TGbH7bmrf6ZRp6blfgFaWFuja1cmmEizZB71cEKIUIbttdRI/GdTMHBpigCs1JNxVV1CweJuHHogocWjLLPBgMyrXF7IuzTa/gn/endqWko9v9nSjmBOxHzpq8mOq/6Rl3EXb/HcuJgVeQtyLUlMyCcGg+IUyynw1Lpa3QsYzpu5ZSYaNCF5GsxsiojwMl6XfgXW/fg+Dw4BUsg1iVenq0PkSPweC7S1onPQkNNgw4jQ0bVNkCTLEp03J7Om7hu7uZVYyvE7sXz53ExdMZT3dgtDJ0lYLoL/DI7NOyjL36/1PbLn7cZZkm7NFwC6Ha290cSHz4f61arPn7+6VwEeziJ8Su1+XTCRJHe/d4xwoVD3sF8klJmFYKbqZh9QEWD2TOv8BCjwnE37+/Ezl2KtbtHC1wkq5TvcCo5I=
    CLICKHOUSE_USER: AgAs4EwJwBFgXaTjtPaE35CoZpnyeoBSRw/7jOXzZgO9v7RJUOoRPLUESe7AVUqXHzCWgpjwOZ5sjTU5663puZP5YlMDHFxRRKQ+9SHMIGchFIgj0IvJN9fy28zvSxstiUGIIhAyYhhyrwmxV83xd0RP/TMoiuoOqzs0bDyw0czJAZfOmKSXOyWBPSP3I25/HZuWQt/+LYnPwj7ZVKy9CF9PDACONuEcIqKKeKwdSwtmp5QFRLy4AivAwVaTWsNWClRpE5sVjjGKsGMoFdKACSLbW99vwlmEmeNJy3OQseLighcaL5BHqTSmIQ7K9VZ55FwS/zdcKL9OyHq/ug7Nv+hIVB9pqGK7d/Fbaw6cJcs06UQEL5XRqbPM/HkgYKn1tsFjx0Ifn/ekrNc3zHszopfJSM9LDW0oDnfrOMrXH+T3ZgnW2XdqEoKZ+bqEWxte0xYIZ8abwcWBSWYZGM0ge9mDdcbeyCG8gKKNhuRFWjPUKLZoIXT5C3+Knsr69wCpdMmEAehAK2f6TyESEMFSXi29r1YN7+J2GgEkJerg/NVTuyLvJaEV3LWwrX7O7PVCrnHdOZmQTAarIwywdTjq8ZOrCS8WbpKKOyUwEYmF/M4Q/zAWtseuMjsoPY1LSmWEc5URRvshW5UPrYA9JQyrwIinF+zISUw9NKJ0LO/fiL4Gy5+C08ZHo4a24GHumDN++T6qmjawOHsH320=
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-credentials
      namespace: openpanel
