---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-credentials
  namespace: openpanel
spec:
  encryptedData:
    CLICKHOUSE_PASSWORD: AgBT1ZF35SERtS5+wTXSOz7bQeCztWc9u74p5WvhtPXht2o3+B1y9BleUn+67tJe/BBDRS3e2pDy4aTikdgwE62kuElZND1zxfXpPu/CRK+xVoHytwik8f0hM3XK7BbFQVJl8t28P0uzOXgJCdE0hym8/Z7x7qc6QJT4tN7iD1xGzdCk+taSZGzqb1i5nyxCarwxZu3wSmZWs8lMU6Mze6Nxyy9QYE4xz5gqbMn2tv/DcXHci03ULLwYlhjQ1ejPadPe5prfOVpXDeIuBzAR2b01y3YzuBZpFEYKJigR62mBo4pxg/EZRd3o4pt90sAWo2bZaXqgTjd1satLS4CzgevmjBirhVHlQ/+NHBsWbBPsBfVF4JyzCuvMM0unJHLMLIvaRBlxg1qz+PBu3KsTNdHjIeeKox2ZGNo6iSYNjz2LML/1Bsntw2mB0HIQa58cHNgQv2QAUETYB7hSJsc7ozoP8DKfCKkdFusVLAhyVj+UVj7INReAM/2mYDtWvjdnq5iwQG2E43c1Jfpabzm0xOejG4AQBrQt7kJsR26NLjV98X1tNInJVI1LbpMm4O/qx9uJmHqkl7AGRsPwS6sP/HA9nUrK7mCGs/X9qyFKXSSGjH72D0ycO1uH/5lVpMzwvodXaRzaALx3wj2f4VMvku+F/55cLyeAILxJNBqq27zWkIAS0tEMGEJSgnXCrbsDHwowhH1V0gnDFUOc
    CLICKHOUSE_USER: AgB2O2YK4aCEwVvMbPteaaHPQtSvAVaSksyQBQH2oXNdLNMeRPcrEvMZHL0XafLY+bUDwKrsq7ztT0sXegFHynddp8JnTi7ymvz2su+4iyHhIN6i3PYVEVrtCjLnUqpPKepNvEoNwqDrGoSnIjFgLxdDkQeZrKlZ1qAs7jtcvghGrF6Bi/jjpHc0JBqS7tdg3S7EE3gMV5UVrv1rTSGi/i0ZtTE+0ycZArWMd8x2iNqIuYXB+pzKVoVB0HYAj/WMTgsLVPPd9+UlUQHNA4PGKf1hZ79Suc6tc8y03rbtmjG6AD7blJ5lTDfubkDOI0byuNW7vIxippwjrRjzGLVxnMBUbGHhYasAkrGMEdEUy7Z1zd8n+99v+J30udKchaPs0RkKZd3tDgRbLrfRcmDM1SnCniu76gak2pSkwIZk6iD+jyLGnPwQqvtipYAohmoNmF1jxZWPwzx9n+qBxVRSfPQPcbtWSjs+KmRMgFjyIvgy0kyFHV/LYhezWEE4lyw4KsQgqi5iPLYGeBx+dKJtllU64OJqbCS1hIPS9ESjCQLKVBmMQqtd7gsgFcLgFkjlZ5xniUZEk5OPs6flxl0Car6gfcSg/dLNyQaTc2ZMKK6abV3Hjzxr9AYRSkhPRHe29BhSRNbwmGwCRvr7bRm8IvpHKx0MetTTgkIXKmQzzwkRI332EYo1vtACM8AybpgyK3m5t3+vSUbjowKl
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-credentials
      namespace: openpanel
