---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCJLN6ruMQKA702FZUsODZDrOHVQPCiMYC8NsqL4M61XJgN7K8wqup//t4MFQDK3V4QMxBschjwUeF7XelmN1/ksmWS3LECVhULdVq/O9s6c2ryFK9M3307o/LU+SuP8dZfoHYNhwkqmya/3fIS+k/8cK3dC4rOQ46HfzE5ghGL8XQkR4U0bNW/+PvC23cdpSpTDTfAcEv2nkHS2zdZCOhbZk4f3CNOi0zz15VOyAF4a6fnkqS5bcN0AouosezsLu3+O2mFJTdlVoQSa9oSmDIioPcAHTSRfMsth8n39adiuadXtbpKmIcTGNPOMXiIdnDsEfL/9iL5SSl0urdjvX4dibml+inqLoiHRwQxPq8h689AGALJ5/2BIOgOmOzBu90REjnP6aAUu5TYS4fjZgJP77cBMHUOxVmdEcG7jz1vjAeo7PqNVsI1EaWtFBxPsfRxvHi9Smi+AzQ/KXy82+vFh2Kig1MeK3VduHf4KIb4FcD4Xb8bU6vSm9skEhjt03BrDmgAnM6tlQm5Jtvyl9zHVzzWCzCua06J2dH/C7DQFy7jB7GOqmLfblf3DdbrbJFDSiTKGmKDLb3Hl2Ks+msXD2ejEqbP8hJdYOAIi1jT00Wjx6VCVta0u0Xov6zViHMCKgLrd7G5EHbqBCgKrm9JjeSGF5ty67pbtz/5Dv3w4UjqMOY3YhPJtPIgpfTyYqQw3Zouob8YJQ==
    admin-user: AgCOmRpmlCTThjNEg58ACIdGLPq1fnreq2q9d9Z6QEGeEarWaJ/Tu4i4U23Ka6H3IzRDy+CDrKQyjfWxbF9zCKF+Itxu0FEcbUbfwQ9SzDg6wM6zx1ZOyKFqOF9oq0y0k+GzOt/in/nYgoBJiXEScGVkLdxzyeB6YWdsGIr+/BYsGXNbkQHCacMRqQhynyBgu3UBDbHZUPGvkXJ198c25wp9qSeugTh76ASsuc+SHjbTZ3Jg8WFzW2IzXdxJ+tf/MoT9OPUNJURwqrIikoZmtHBYWrdzXOmayHyphWl0Z4VoALfNzfKb8MDifaRDUrbNzBw1WXtgrngx4VLWL5TNvx3vWCu8xbsd1TE+PUwNe33HOc1DkM2oAVtYwFjVRctrfiwjhur6CvtOHHpsYCIAvlM3zz9ZAp8RoZg/4ypTIwmab+vvEgVhrHa3AloJXKeaXa/XQAoHA1CMqBiFcD7XuWv+r858osuYbopJ+38cgWhoogTOh6U7zFtyzrMiLCHnEXVX2vCRsHPQ7GAokafWGFQbJxV8hq0XHyIvmuwDhdIgkT6JpDCH+SHUfq5XfrAvTkD+NLyM6cHn3xTQSFmIw9bznP55tVkc1C8di2fFQLBfNrrhrWIYbG4S88+br0S8VJIdo5EwvnlGWS74dRckg6IbDhl7C4Sf0w0gaRZVPMCSqJkuCmu7692OzIbrd6/8e5MdcGk+gw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
