---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCVpDvagnbYD6lwMmKdOnF8KMCpIj5QVEyx9/9XX8222wiwBmsEipk16H6/9i9BDwt5xuLfFRE7kVAS47aLQNYBmAroUAFSlMw1ZswZr4oHUVrV4d9VA2OieZIXqbOqva8/ZOS+ruKWblzTvi6FiKg3Rk5FTw1Cx4dZGardIi6xu4ZAj9Zfr1GK8DnBCEdE4ZCrxO7Qf01D8Ih2XpVgPOrEdkf1pVVtVF1ePddMdWFzZd9Y84C843r5s9Ux3oJXsMTopwwTImfQgapkIczarfrrcDKPj78ZqWvAbZ9bnZ91QR9z9lF77WHVHP22j9QaTVKA+m+EqgRolBeU4VmIBtosfNrFKJzRrDn2LgGifdfR6fRBvbvfxQxxKIP7wpXdU8Aw+a8gn3DN4zGrgBLk1PwlEiOK0gfeJEeFFIcCdVQi6jWnltJGRCadpwTkJELmIK6ABiik40AvJ0qNdODvIOmzzS4sIRQ/wKrcydn2DqKBezrHVMkn37iJfckOaCIkLNMqJOKk5ftYeT+L3ifbZvMLt3Bw8udV5Ve0BzwvGGjqqzwnhOq6G8jr7G7S5f2AOF2wz1EwWTWUIE97lEEo5tdYxepimdojx1zE42Fue9Scr2y0d8kFLuSXwXVsKQvS0p/modt6UiLYeQm1jNJw/hrtVJgv9Q4PjLkLw2UYILlxCw8qzH4ky01GRjQBrMmFdK0/T540eg==
    admin-user: AgA/xJ0h7O6/hV5IBtaRRETggp3tnyQ3He17har7Wlgb90ziLRBemmmggN3K9xL3IcXkruvMKhH5Eew7KAMfzIR1HpEg0xdSvQKvkbTaqshZtf34wp0KbQtpEqrM61uhXPxQLkcuPXpFXnyyFOeUkNGZbDlwIiNroVvMI5CkRFyqFPKqh0E5yQN48DHvRkAZJEpIHvvAf7g8c76SLWjqg8TVucYZrFy227WehliPvP9Vj0NP3MwKuU/v6Wu8KZKfIzlIZmD8N1K90ZQtwo5NPeoff273fvJn65ni5AsupJq4eDkJRHtd4cx24D/10HUhO9Q/iaot+3V2Pi8fbhIX7IlEKAMdv1jCvvOzXZndvYSXdvRjSLrgPr9E0eC/V/TsZUZssGVXk1Iw7haP4Yo8rgU3vlHy/VgUt8ILhgWSgtAayTSo619ngDMYjWWiBQHx5oAmgUH7KK9bthgbEW7j9J/WHsgW5hOUuiyLhapob//ROSQXqBjZxkuT09ETU4XuC8nCCD2upA339EOhaWHWUZ3rnXa52vcAwC0P0BGGUVsNXZIaqDURYVo/oi8RdFiBQbLphMxac65nPq5CNPwWe08DEk5rI83dopqGEEsJ/Jy+69Ry5I7M7nEazKz4T/jqJ2W4OdPmrZxmgzEJS5ihNtcJEY/ylzFReLhR4cjfqPnGmL1Uxr68aypP6oB5waVdqy8m5Yc39g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
