---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: backup
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBYQZjXG9lzBJ+UgS1ojCjsPQ+z9pw98JVC/zMmHONU3NmP8BMuv4pnLut2xSXPAw8ijBTDcZxZlhMCrz3t1YjsDunx0W4m4I6DZsxKUJzAlJq7u1gAY6wfHH9yAOMGzfYfe9sDDukkSIFXhmLjSd7r1k1V1r5wW8zrF01AxochgLBgtPSicFQmmCg3VC+sYlKGc7ydL36pdxWDBSMPdxRaKGtLRTcpIRGuk2gvDQ8sdhfgsTuzHdwkNngOtD+xsBfMk5MGEs+2PYT3Mx7t5+9zSLrV6wUV3uLygV5SKw1gtD/40HbdyWCiqjZhGImo1gnA+f7WfP0ImpBcOArpMhkmjVs9+ANkb9ahcB0B+CW7dORx+m5s2zc7C7O6Rvx8JPkmh4859ApEDHP98pJ8tAemSiZea0fhT2rf3Wn7G69jR4lm3bkvYPRccLkWpiLfXjxBcQoMUD4bgdr5zS4+YGjUqQhbHdqXNPWb2Sy+PBXmWDaEgiTMe6iyhUuKKU74CqiiLEEarLLD4N9F9cmU1Vjyzl/OS37fp2t68iHEaQeXdnSsN/+dG3I1jNoB75Svo/2uFxaj7IMxOluZc8Vj0f0WwAcZtwpuXLQa2xOICKTkr9O00D46ilmJeKwnBTtoO1DhkWlM722GwhOA7Y4UasNtkTTCzskNqscYuTqfLjdOWGc0kSo7uB23QDDWm8DAh7moNWh1I/Zw88u7h0QcaQ6UXg==
    MINIO_ROOT_USER: AgDJLSRK25zhmXEtivjGgMYUEsLdUmypmq3CcojMIywzBIrqZX8XLPkdgS2iVFe37mEFf392Ww+U5pa39FIQS7/gI9yyEhEYcKk5gCgoL7YJII+xDARhmv/vd+NArizAeP7DKqCQWRAzPwbX5+M7WWCvc8QhP01kb+TDia9l3UpKJHw3FQoyooy5F2QXB7EyGbwQCGTnXFVpu0uvhKVQPNUUPp06T6WoQQxYn6oklwWCveONoFJBeRvPMFnL769+C7S9FjCZLfdIXoGx/K4ZMVFxHohUai9GqXm+nHZz/FL1dMD4H8Aihr0hIwwA08IYjbc+SHBq6uY8+TWDqGkIvu7uXxhwKF5MGtoglzU+yiGyDe2mOJVkCQS6EPkKyGGcUBrnSJHWAKBKnN4av4ywH22TPM8+ML9SuZH9h4CBydx4d3GbvAurFSPJfMSO5CV/mTp/EXBc28MV/AwD9AJY2UPdHHwEuNZIm8hy83IpR2yeS5bMTlAcQZKyw/K8yupNYdI8u0129Pn8uv+HoJYFwvkkSRiNIULaYr3MMNpDqhzWnLVY2MBr9gc9S1XAp2AMCyNGtQH44rfYsim16oNg7QBN6fjRadztJKK6MoMlzxVmb12ImZWHLrmR9hu5mqBBhdJUrnhOhuBEe6xQgjYqw0PuCuSu/Pla40d5JROcm6UxhTFWD6PODBCoA4iaNjmNeERGF2XVJy1JC65X
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: backup
