---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: backup
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBuJSopFp+H8GXIq+Tp4z4YTUs1xhn1Z++WQ3P4tfV/mVUwZAb/tpYL5xbmmN/icItjQfNiHnmShyQqWM8UUr7ygPvPf7A7s/KCXnta5JNFxBvfbOb7vUx54uBId0Ym2q+a7VyYn9mMXkU429UkMix9PTgVnrSToemg9TFmczhjvBuwOWFMBYm83qCSxdy1xpznDt+tQ34rUURRyHGvbQuQlEOG9lXCfEGR3NCKXAp5Kg0j1A1MwlnGMokvRDTh3H+gu76KKp4BIfi66b4FFCgQLMj2IX12dtUhp7b8Zp2rzqXBn76qrjFcbevlpTk90pxccSLdlEC6HW4aD0TTEUlvDPuZf+WRqhSedLf3SbCopRiXJply4KBszgQmJABkD7sHHmFSjy9Pn3QbULbRb5UsNGPP9Loru5RjrIWqK2ZASU4aXrhnKapX+5d2+Z24+3LgsPj8NXXsPW03GRyEsUGVryyTyT11pzALyDW4xzDCVgYLAP8Tc00mtjJY/m+5IiAwW1SKiLcp7UIgQaZXkNcaLXoyDmbajJrG1hWy+6TXExN25j7CIs81v3gN59WavRLoZznNtkIF6fWgoquGsixR9gQfqMjpqktICuqkwRI+p60cLKyIY6qoG95lqqto/g9JT4MyDZEoUjTklcOsU6tYxggg8bwHnxzsVXknSOPtD/fUKfrXGCXq5uMpo7teZzLN/nO5I6XJVA==
    MINIO_ROOT_USER: AgBKlI142BC73tomK49VDh84z/mtaWvv5Bo7i6dUZqJ5vmYoI1wz/EKL2/C4Yz3baItXxX4XvF8Q+53/vCAci4CYyuy+plwuCMrUVIdRPKGzN8uG7a3FE/OHGkte3Wj1hMxe9OJAJmcUKYeM4dxxZE+x3C64MQnKAENbM+MnsZek+7HFZSDR0z7JaOAbzL7Y6EdHLXL5h/BNV0q+QewQAuSfCQwrL89BUAElxkS4AQrC7R5iqV9qwBD8aW/j/gD9+Z1F4V+tUl83mkN6Y8UlSBQ5nbwzeGgaSnJbeRK8RLGKA2Xevw6MTAe/tfzVFPx8eVygdPLpg/Qg8P4zwmA/kV30kSXGKensyGTgPYs691BS48eBbYeQ1ZTrCApG7Ch3LSczpBNyRG4HSM7oEG+ct/ZfDHyP8foztyPMmq+uqrAQzrLot2QbA8t2FbBB1j7mT2M/MSV6NZA4wnn0mTXYI6KyvH6U3MRFaohNaN+TX0NPQGwCT55gVlVxIV6i48hYZ1vjBC+K3oER/Oj9JDdEMAniSxyhk8QynkO2xYSQtrpCm9FFiE8XIC4+5vLTGaInCLhl4sIrHh3KcU0jk6Tsuu2SvJ/SoOqwJji5UCkZHFuZhPvVz9CRuIhaYECPhc2hhmHZANC8AN+adV3Xzonl21L4UEiORmUlwP7gsMMYUcsg3B/vCxqEzqqcuyr8fWHAmddmXCt6NQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: backup
