---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: openpanel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAi5fAU9mgXc9miwDNg7SXL9mCzcQdkd18sO74XsA8PnGlYShk6mdjoryFVXfi7IdJLGQu3x4oGdPsvwR3e5NFH2k4qiMCSKLTVwl9ofH7ZRWFfYsE7l9YK5R9xsZygOJgYfYtnK4YghMpyP5tCWYr4Kf8yEUHkBon2gmGecefL+OjKyvynxhcblz9NcOjjgBE0YvMLjqYOZ2hx6KyxZwPfJ5lCp/hUBw/IMqhWJBRgj3Gas1bOTySVJezQPbQTX/RUeD4XPCrDG1lGL2dWcfeHOU4YJWPWbYjCVrQPiejKu57gZu7/5ZWyuNfNTMLq0xqmluJtlMh+bScdOMRsj5fPxbsaFmB7HKURwy2W4b5fgPz/fRx4dpmnPgd1Eh8i1MmTOrn6sw+Uh0qcFA+RSzfIX0DiziQb+npebodCipU/cVRZvHtccSkmyOUgX7Q5WvDzWtO1xYIo7MxsSe1RWrbN9fh5UqJo7NYDYaV3M4oOAnFWTP4iwdNURjyFgWVIKmjPHBaWcdF8KB0m4Mr88n1limyBMgP73SJpzJsKScEr3axN2vaVwvs4jPlf9F6tyeOyJqWl1jGp9hQfhenWyubz5L2fqdt2SH0HStZKTyrUe+yxRKR2oIqWhczAzd39tS036scKs+eCGRxdBAdd6MYpZ7OBT9nnR/8lEvCqyV5sczJMvWqbRoItmUT+MHeXeGJ5HVZd2OSWOQ==
    POSTGRES_USER: AgAEuD6Nul1tN/xhlpYET+9zUudmDR1fkNN6fbtfW61msjmDkktzg7Mw+tWyuIwbA9UbsZbXWOx6hDIDjRKm1ZnOurtb3ux7xBbCZw0Wq3cHMFn7TlQgS5lPX9iQwGdcsqH6RCcS7MOwqju1FJiujEozIhlU71qCqt/KLoM92/RmV771+5FGFGd0KZ03EuVIhyEJbqIhtitBBMFUDuvLSVm3Bj6PiFmnJhBkK7CoXboWNtMqQH+NLQTtC2u1bq8ijjSjKB8l9xfxI3cew21s9Mphc4qUuDiHQAQKwmYDGMUbxkNHqoAh2mwUTlsJQwuBlGNacP7u5dJqY2kANouT7pq4V/3zpy5F9IKGOs5CwykrdmiDxaZVyEAViVkusfm2XkHGuTP/w8LKSiQMO69p9tSmT5DtUtGNGWjvk0a2VaxyTUoqr2LfKW8wSXnTuQfObCNqJyMaPNnipr6oG7vyiZyJv03EqYbuwNic3hFUOs2+CgI/uu3dF8/ZOeZnbiFFW2lLrhveSF3YL+JFzypMWabdbNdlNUvXtcoMrFix9u5dXaSBqShroxBsXBy/f/QHZWfiPqDAZXijnM5w7dlNpisOj+fSrG6K0b+RrKY0doj7ewg9GhzdIyXWuWEM9OgzEOeyIg+j+vAatjSu0nqx4IKOn4RqgfTwlMC5koBswEFqwstrPQKtlxgMlnd7GLiBqr+rYWLc+gLpHw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: openpanel
