---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: openpanel
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBzq7gRXbCfxB/0VuD+l/WLuG0GKDHwqesFd3OZqu+WSU5Mi581n9dcvsl2OSMCP0hZkb6VaSFEvby62gOQ+pFxuqzfoENkEgG9+KY/nFHDnD2/VluvjAyPQg69cBEL409K0tbunwRqmI+6ZL2O1TTZBLz/1gydDxLqH0FGJ35JUwSM7tZpbm5ZN5LuJ4GIIlikH8kmjeNtOwGLbEX6KymbtPCCATNqgg+As3xCEDiTqAo5tCYzwoNB/xtJ3/t/+2D/IljPM1UiEJ+WFasdEr+7lWy57zTucW1wwyxA6nV06BYSU0FTBf3cApGfWieXbjJeP7jJ2BwH/6J6YxSVx/YDHtY29A1aPX+3CdaIVdrbRAXDyFJNLCNIlQ2Rx9ZQbA8tDZ37L9Q5qFYXHx20lQr8Ey1kLxUMLuTvOe+ZYtLbHDmbxwylEb1TYQp4v00iW2f0ehoVBVWz04atV/DAuDaTCp0cyG1CeclXBGNPj692bqPbiHzmf+nPXfpX9lEXvTYPFJt/el3EJi2oDn0kWEqxju/vldXQs+hzaYErJNNCvXduE9MshRZgYQLFsGIWDtY+Ld07tAx6DDy1DjOZ2DFB0f7/08Ctk8x9QjnqDgm0DrgHX9szYUw5jlCowI7ug4b8NiQvZwmeHE8EN4RdId4Vn4SMDZ/t4UcO7MDzDp2oGV8/1BigdVvY4POWT1hGCiE7rpLBwS5ypy8KTHs=
    POSTGRES_USER: AgBPUUfDpsCxXE2h4OKQ2cqOVDz34rf+CBLO9Dc1mWcl1mWs2s1wWYCcEm7ncVgQjXVGOBnOQMQuEjOFPLrhvuUuAEb9k2jLMDp52IFiUpHsWxFPsTOTP8D9d21eP9SZk6QKRgmeXW8gNDmlaV2uRXdwa5M3JjqhpAtczq4gFrAn2rrmLoiil9ycH2JXl9QaVLdvxatOTjZ+KLu20CeyWyqff/P9YdJI7H0L0NUaIa26FWzvd+khDwEk/Xe6E3qpwP25vnNYB1n0aIxEQrMd8XL6yGf5RErI8OoK99imFIxR7XHkAQPWqRAGMpCny8ALVy4k9TPr7tSiMqDdQSGlkiDIy1o0A4Zw1Cj9OVs5vB3Nj+241yPh6oLciN6Iz3KVkOzS5taMj1UrXD2fS3T79D0x5smC+LGzyMQJl/2XnhwOTshZGCN503Ylhrj67YlYkE3y9KTDHkrGNhM3ue21M5hIKdb88QtR3NzHBp5XJU69hWgRJasY9pv708CBl8yb+sy9WvbzsZXYvSV7n0YmLzQzqsmWzi+cAfdNeXRImUC5EPr2CNdo1B49ndqCYbXZg3BPdE8pPbJBKMl/atlcFaK06uHWArOssr9MKrNRNpb15R4L2sb0/UN1leO23MdYratHeACQ6J7cjo7c7HH42QPnKC9zfxuLj0nJscWMP52C3ZnSIjzsYB615Ch1a2x2VJqNAnX1U66pljk=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: openpanel
