---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: openpanel
spec:
  encryptedData:
    REDIS_PASSWORD: AgCiNbuaz/AG9gqdKL8pHN+N6t3NmOfuJsX6IqQQUSkAm5TAYseENSwOFw1+M1yVkf/kvZyRUAhdNUPcHU2GuoIQkeD3lzfZvV7BSef7pnz/XfjOTEYJznuBSMJgtXbFgQFNlBKa0Skz/fz6z5duMuazBP1Q4Bb5BfXX3fLm8EEJC3sJiEPLW1EHKh9+usRNxMkl6/sch5+veBxqBXOpaqtfW/cJ73lDRV8ZHt2wdiv22+4OtkwKPy5acnX9It0otVE4fb4p5eazUoSVHXYbckUP2JHgJjY22QzIP/UYyGMMmheNDmW3q341PbbAGnQ6ncG+7nJRv7DzdSPG65VcnQkxfzGdA4VF0akl5BbQU2MT1T5WFccTfZNI6FYN0Y1PCSVD/K9r+Lc/YK7XF5cLoqCxqkiDkixvyog9+ygbGzQ4J9aFKJPPhxCbvFJZQK3S8E1+HsWcqBHdzbK+HDRQN1IQTU+LDr7mT9ZEhB5H8bvpPmoJ8Y8Zn0arzuugTreSKrTU06/5zo4eKwxZ+wusAKpWWqE+cjQjm0EI8sU4/1Or9NIMUcc8PIcUfOk2S6FpPnmXpiMFyI6dmVbCSfuWRnW24ZC8k3vdiOUD2n3r7/buPnB3bLZdS2Xzha/naOl4FNOnwRYxjcEBYcypS6xhRZpF3Qb/L1Zi8U2/r5e4GlBkYph4HlljkNXUBhIp1Sn460bNZRMNIKxjuVVQZlw=
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: openpanel
