---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: openpanel
spec:
  encryptedData:
    REDIS_PASSWORD: AgB9FtpKCWRg8q9btCyhis90IS3aJ1663ucLPyBAsIW6s5hp26qmgzwbEmseVZ/2g41ahnP458z6AUXlmgM6tiUy7a8BCPaO2O9sxbXAEhCTf34nvDo4ojh1c89j2YjzfQ9zqILNENiKgVfSMEGvOwq5orm9KdCXyujjzjkO62Xh3hEW/kZ1+CMXUEpJTwYRl4jjQrN4EF+08Chr39XtgIDiJP/8Lunm+5ldSId52mwE7l8z9N1qtLq9yGbAJi6+8mPaaCa2eqN5M7R2FIcQgAju77y4If/wDKhKEi/YX9N/HUwiwW4F422I8VVWuwhs08b8tdkmkHolpnpw7f/h0mkcT7AoEX8oWOOoR3wmGm4Pe6mPbzqGXdIeoN6Kbw3wBJjcXNGNm81AF/5prVb/U5UBNfHuqQPIMHA7IrgidXhxSfpbx81gi46io/vs+HpgH0+swYm55sOnbqGRugfIkcGAjkCwdL56M8gssHSwsUJRQq4zJ/DGKUn3KN/ZfiQuIfpt7jDuDJM9hykDOJAHzFR8o6gXUDIdUaegxk2GjTdEPRmpOBwuiVBdEvRQCr1coSrw4VunabjpK9zMtXITJgdDoxCB81PHjlZ3Dn6yYrZDxLGoPwiZH7g+nxLI/DDX7X/WASKYN0UAQ0GRF6xqzci4z1iXv+N2zkl7SAluRGmpkq9UFf15U3k+CCUZqnToaK868bZLRw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: openpanel
