apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: openpanel
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.10.3"
      helm:
        valueFiles:
          - $values/k8s/helm/values/tempo.yaml
    - repoURL: https://github.com/RubenLopSol/proyecto-final-devops.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
